version: '3'
services:
  go-server:
    container_name: go-server
    image: gocd/gocd-server:v17.3.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - "./go/server/godata:/godata"
      - "./go/server/home-go-dir:/home/go"
    # environment:
    #   - GOCD_PLUGIN_INSTALL_github-pr-poller=https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/download/v1.3.5/github-pr-poller-1.3.5.jar
    #   - GOCD_PLUGIN_INSTALL_github-pr-status=https://github.com/gocd-contrib/gocd-build-status-notifier/releases/download/1.6-73/github-pr-status-1.6-73.jar

  go-agent:
    container_name: go-agent
    image: gocd/gocd-agent-alpine-3.6:v19.3.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      - AGENT_AUTO_REGISTER_KEY=2aa214e5-0a61-45ca-a30e-79b956764aa8"
      - GO_SERVER_URL=https://go-server:8154/go
    volumes:
      - "./go/agent/godata:/godata"
      - "./go/agent/home-go-dir:/home/go"

